name: Generate Auto PR

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  call-auto-pr:
    permissions:
      contents: write
      pull-requests: write

    uses: tspyder7/github-actions-lib/.github/workflows/auto-pr.yml@main
    with:
      pr-branch-hierarchy-json: |
        {
            "main": [
                "development"
            ]
        }
    secrets:
      GH_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
