name: Enforce PR Rules

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  enforce-pr-hierarchy:
    name: Use Enforce PR Hierarchy Workflow
    permissions:
      contents: write
      pull-requests: write
    uses: tspyder7/github-actions-lib/.github/workflows/enforce-pr-hierarchy.yml@main
    with:
      allowed-branches-hierarchy-json: |
        {
            "main": [
                "development",
                "release-please-.*"
                "hotfix/.*"
            ]
        }
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
