name: Release NPM Package

on:
  push:
    tags:
      - '*'

jobs:
  publish-package:
    name: Use NPM Publish Workflow
    uses: tspyder7/github-action-lib/.github/workflows/npm-publish.yml@main
    with:
      node-version: "20"
      registry-url: "https://registry.npmjs.org/"
      package-manager: "pnpm"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
