name: Release Changelog

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-changelog:
    name: Use Release Please Workflow
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate ChangeLog
        id: release-changelog
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
